<a href="https://colab.research.google.com/github/JEEVANA-MALLEPADDI/fml-session-1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy->numerical pyhton         

  Numpy is the core library for scientific computing in Python. it provides a high-performance multidimensional array object, and tools for working with these arrays.

  To use Numpy, we first need to import the numpy package:          
     import numpy as np

In [5]:
import numpy as np
data=np.array([1,2])
data
data1=np.zeros((1,3))
data1



array([[0., 0., 0.]])

ARRAYS

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [73]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [25]:
n=np.array([[1,2,3,4],[5,6,7,8]])
n.shape# gives (2,4)
n.shape=(4,2)# we can also reshape using same function
n

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Numpy also provides many functions to create arrays:

In [74]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [75]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [14]:
f=np.full((3,2),5)
f


array([[5, 5],
       [5, 5],
       [5, 5]])

In [26]:
r=np.arange(1,10,5)#it does not include 10 it takes elements between 0 and 10
r

array([1, 6])

In [23]:

r1=np.arange(1,100)
r1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [76]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)


[[1. 0.]
 [0. 1.]]


In [78]:
d = np.eye(3)        # Create a 2x2 identity matrix
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [79]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.97959109 0.27123108]
 [0.91740119 0.14945679]]


In [24]:
r2=np.random.randint(1,100,5)
r2
#5 is the no of elements you need
#1st 2 parameters are the range

array([84, 19, 43, 41, 22])

In [21]:
r3=np.random.randint(1,10)
r3

6

In [22]:
r3=np.random.randint(1,10,10)
r3

array([4, 6, 1, 5, 8, 4, 1, 6, 4, 6])

Datatypes


Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [81]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype,z)

int64 float64 int64 [1 2]


[refer this to read all about data types](https://numpy.org/doc/stable/reference/arrays.dtypes.html)

stacking functions    
vstack()->vertical stack     
hstack()->horizontal stack    
column_stack()

In [28]:
s1=np.array([10,20,30,40])
s2=np.array([5,6,7,8])
np.vstack((s1,s2))

array([[10, 20, 30, 40],
       [ 5,  6,  7,  8]])

In [30]:
np.hstack((s2,s1))

array([ 5,  6,  7,  8, 10, 20, 30, 40])

In [32]:
np.column_stack((s1,s2))

array([[10,  5],
       [20,  6],
       [30,  7],
       [40,  8]])

nuimpy intersection and difference     


In [46]:
a=np.array([1,6,3,8])
b=np.array([1,2,3,4])
np.intersect1d(a,b)

array([1, 3])

In [47]:
np.setdiff1d(a,b)#array([6,8])
np.setdiff1d(b,a)#array([2, 4])

array([2, 4])

summation of arrays

In [48]:
a+b

array([ 2,  8,  6, 12])

In [49]:
np.sum([a,b])

28

In [50]:
np.sum([a,b],axis=0)#if idividual summation along coloums is required then we set axis to 0

array([ 2,  8,  6, 12])

In [51]:
np.sum([a,b],axis=1)#along rows

array([18, 10])

basic additions,subtractions,multiplication and division

In [52]:
#a=array([1,6,3,8])
a=a+1
a

array([2, 7, 4, 9])

In [53]:
#array([2, 7, 4, 9])
a=a*2
a

array([ 4, 14,  8, 18])

In [54]:
a=np.array([1,6,3,8])
a=a-1
a

array([0, 5, 2, 7])

In [55]:
n1=np.array([2,6,10,9])
n3=n1/2
n3

array([1. , 3. , 5. , 4.5])

In [92]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [93]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [94]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [95]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [96]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Mean,Standard deviation,median

In [57]:
k1=np.array([10,20,30,40,50,60])
np.mean(k1)

35.0

In [58]:
k2=np.array([1,5,3,100,4,48])
np.std(k2)

36.59424666377065

In [59]:
k3=np.array([11,44,5,96,67,85])
np.median(k3)

55.5

numpy matrix

In [61]:
n1=np.array([[1,2,3,4],[5,6,7,8],[1,5,9,0]])
n1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 5, 9, 0]])

In [62]:
n1[0]

array([1, 2, 3, 4])

In [63]:
n1[:,1]#it gives thye elemnt in index 1 in every sub array


array([2, 6, 5])

In [64]:
n1[:1,2]

array([3])

In [65]:
n1[:2,2]

array([3, 7])

In [82]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
#Two ways of accessing the data in the middle row of the array. Mixing integer indexing with slices yields an array of lower rank, while using only slices yields an array of the same rank as the original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [83]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [84]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a.shape)

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

(3, 2)
[1 4 5]
[1 4 5]


In [85]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))


[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [87]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [88]:
# Create an array of indices
b = np.array([0, 2, 0, 1])
print(b)

# Select one element from each row of a using the indices in b
#print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"
print(a[:, b])

[0 2 0 1]
[[ 1  3  1  2]
 [ 4  6  4  5]
 [ 7  9  7  8]
 [10 12 10 11]]


In [89]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [90]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [91]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])









[3 4 5 6]
[3 4 5 6]


transpose matrix

In [86]:
n1=np.array([[1,2,3,4],[5,6,7,8],[1,5,9,0]])
np.transpose(n1)

array([[1, 5, 1],
       [2, 6, 5],
       [3, 7, 9],
       [4, 8, 0]])

matrix multiplication using dot function

In [67]:
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n2=np.array([[9,8,7],[6,5,4],[3,2,1]])
n1.dot(n2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

You can also use the @ operator which is equivalent to numpy's dot operator.[sridevi mam repos](https://github.com/sridevibonthu/APPLab/blob/main/Numpy_Tutorial.ipynb)

In [68]:
n2.dot(n1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

saving and loading

In [71]:
n1=np.array([10,20,30,40])
np.save('my_numpy',n1)

In [72]:
n2=np.load('my_numpy.npy')
n2

array([10, 20, 30, 40])