<a href="https://colab.research.google.com/github/JEEVANA-MALLEPADDI/fml-session-1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
data=np.array([1,2])
data
data1=np.zeros((1,3))
data1



array([[0., 0., 0.]])

In [25]:
n=np.array([[1,2,3,4],[5,6,7,8]])
n.shape# gives (2,4)
n.shape=(4,2)# we can also reshape using same function
n

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
f=np.full((3,2),5)
f


array([[5, 5],
       [5, 5],
       [5, 5]])

In [26]:
r=np.arange(1,10,5)#it does not include 10 it takes elements between 0 and 10
r

array([1, 6])

In [23]:

r1=np.arange(1,100)
r1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
r2=np.random.randint(1,100,5)
r2
#5 is the no of elements you need
#1st 2 parameters are the range

array([84, 19, 43, 41, 22])

In [21]:
r3=np.random.randint(1,10)
r3

6

In [22]:
r3=np.random.randint(1,10,10)
r3

array([4, 6, 1, 5, 8, 4, 1, 6, 4, 6])